language: elixir

elixir:
  - 1.5.2

addons:
  - postgresql: '10.1'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script: 
  - mix test
