sudo: required
language: elixir
elixir:
- 1.5.2
addons:
- postgresql: '10.1'
services:
- postgresql
script:
- mix test
- npm --prefix ./assets install ./assets
after_deploy:
- wget -q0- https://toolbelt.heroku.com/install.sh | sh
- heroku run "POOL_SIZE=2 mix do ecto.create ecto.migrate" --app $HEROKU_APP_NAME
- heroku ps:restart --app $HEROKU_APP_NAME
deploy:
  provider: heroku
  api_key:
    secure: "ieVgJwsLygnP38L4xMbcFwR2kq/l+W75Q1o6ZCXrgm2cG3/5J08dxtjhkASf5xDzqEAUiJ+uTg/cSZHBUlDsT7jlcltlmtS6eqHvnzweDUuhAceaWAutOvitx4vmER4zJ0BTb3LwRG0tF8CcgDabVIkyGeY/Mncld72lcwSQXKPTkPedwROjgalt1lovgOweESUYGjNVo8mbyliYNCyZvRFyKu0yWjoN6ssPfL1fBZgnKazn7Se2tVUOiM4MM6N0zBufCwNXin/ipZf8vHvPCOryMb+ibuTSWWRFIXQtj8doHJotKtTte4yuaZhMCJGl3T0HLR2iK5v4sUcXjRbwURxlc9icyprWnFwinEer9dBE6LunFMWg2AlQ2hPxQrNUx8s8WEwgNJ3wlBozBXlCrvmVjW6hPxtssiiDUrEd/VL8R1Dsxa2HcoutwAiw4iyj3jajjblkOrM/ssvMPox+BoFRTaK8se7f2uNj96/pqmpw50z3agqizw9meeB3Y4t5LtO4wL7QuBCkZPZrjytzaxYZnKA6AU0j+GEZMbVWOmPyMxdNcgKit+HJUMKwGyEQqUMVUj5O8frjLHvJCfbJia65oR17vxeV8dA9Cq4ry0cL3JoRJtQtMAJDz5FYneiGCMWcPjCBkCF+VO98JtoTaJstr+qMwkx9rmtEzN9YQwY="
  app: bakesters-finesse
  on:
    repo: tevyt/bakesters-finesse
    branch: master

