sudo: required
language: elixir
elixir:
- 1.5.2
addons:
- postgresql: '10.1'
services:
- postgresql
script:
- mix test
- npm --prefix ./assets install ./assets
after_deploy:
- wget -q0- https://toolbelt.heroku.com/install.sh | sh
- heroku run "POOL_SIZE=2 mix do ecto.create ecto.migrate" --app $HEROKU_APP_NAME
- heroku ps:restart --app $HEROKU_APP_NAME
deploy:
  provider: heroku
  api_key:
    secure: "klZC3j7KgJPCfdzcBobeclOM1JvpkDMJmgl+oMiKTIPKTIguiGK6ebHDjjphfJEbUq+21Zr9KQ3qvJlv9AXn08GsKZUyMwykf6pPQG5FR6ILUawaFWB7OnWRGq1nx/q1cTr02KuMFonQ/dt4Bwtb2Q3lob1+BBQ1lL8gFOZFNEt0ztlMWQDU3/4HCPf7O0iQl2XC22RwD7+azyE8B0M6JceS4jdMb3UYKMuU0Ar1/cRx8pN0uOq3wCUNbZrp25WBxhgsdj+aW6hhgxSxSbosXOrMaZFcX5+11Fo+xRiuEn7D3DCAomy7Om/d7XnVaeZORPPm6RFotGnHAFcrMAAm79T6sb64caSnAH+tlJp/FvZMYmYmD1WIy1R41j/bWoOYnFNizS6XmebdOo1YV3aSISm4Ipgt7U4zYBCzlL/+A+BHbAUI3GkBb5k4HVEMlg5/DJa6vKH4Cuh38rBiuTmPqSK3/NE6gk5LCI1WitkP73rGl/c5q34/7sjQ+dLhXGDtZ9CHKH+3mQ8Ea7MF3lDio8Djup4SPPX2YRbTILqU5hwKrWB/Oa+rEPatvHiUpHvD8swD67islih9c8c2PQ0hLIo5cD3RHkenEbEGTnjMHKAYpF1+JwfTaSwCaZKOf2cKT5s56oZoe41LhPv7RlyD7tpi7B2l1XQrXwTt1yUidXk="

  app: bakesters-finesse
  on:
    repo: tevyt/bakesters-finesse
    branch: master

